/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_afficher (void);
GtkWidget* create_window_gestion (void);
GtkWidget* create_dialog_ok_aj (void);
GtkWidget* create_dialog_pb_aj (void);
GtkWidget* create_dialog_ok_modif (void);
GtkWidget* create_dialog_pb_modif (void);
