/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_afficher (void)
{
  GtkWidget *window_afficher;
  GtkWidget *fixed1;
  GtkWidget *entry1_recherche;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview_reclam;
  GtkWidget *eventbox1;
  GtkWidget *button3_modif_rec;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *eventbox6;
  GtkWidget *image3;
  GtkWidget *eventbox7;
  GtkWidget *label3;
  GtkWidget *eventbox2;
  GtkWidget *button2_ajout_rec;
  GtkWidget *eventbox8;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *eventbox9;
  GtkWidget *label2;
  GtkWidget *eventbox3;
  GtkWidget *button4_supp_rec;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *eventbox5;
  GtkWidget *image4;
  GtkWidget *eventbox4;
  GtkWidget *label4;
  GtkWidget *eventbox10;
  GtkWidget *label1_cin;
  GtkWidget *eventbox11;
  GtkWidget *button1_recherche;
  GtkWidget *eventbox12;
  GtkWidget *image1;
  GtkWidget *image8;

  window_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_afficher), _("window_afficher"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window_afficher), fixed1);

  entry1_recherche = gtk_entry_new ();
  gtk_widget_show (entry1_recherche);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1_recherche, 120, 24);
  gtk_widget_set_size_request (entry1_recherche, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_recherche), 8226);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolledwindow1, 40, 104);
  gtk_widget_set_size_request (scrolledwindow1, 640, 240);

  treeview_reclam = gtk_tree_view_new ();
  gtk_widget_show (treeview_reclam);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview_reclam);
  gtk_widget_set_size_request (treeview_reclam, 640, 240);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox1, 240, 376);
  gtk_widget_set_size_request (eventbox1, 224, 32);

  button3_modif_rec = gtk_button_new ();
  gtk_widget_show (button3_modif_rec);
  gtk_container_add (GTK_CONTAINER (eventbox1), button3_modif_rec);
  gtk_widget_set_size_request (button3_modif_rec, 224, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button3_modif_rec), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_box_pack_start (GTK_BOX (hbox2), eventbox6, FALSE, FALSE, 0);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (eventbox6), image3);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_box_pack_start (GTK_BOX (hbox2), eventbox7, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier une reclamtion"));
  gtk_widget_show (label3);
  gtk_container_add (GTK_CONTAINER (eventbox7), label3);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox2, 0, 376);
  gtk_widget_set_size_request (eventbox2, 224, 32);

  button2_ajout_rec = gtk_button_new ();
  gtk_widget_show (button2_ajout_rec);
  gtk_container_add (GTK_CONTAINER (eventbox2), button2_ajout_rec);
  gtk_widget_set_size_request (button2_ajout_rec, 224, 32);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_container_add (GTK_CONTAINER (button2_ajout_rec), eventbox8);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (eventbox8), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_box_pack_start (GTK_BOX (hbox1), eventbox9, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Ajouter une reclamation"));
  gtk_widget_show (label2);
  gtk_container_add (GTK_CONTAINER (eventbox9), label2);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox3, 480, 376);
  gtk_widget_set_size_request (eventbox3, 224, 32);

  button4_supp_rec = gtk_button_new ();
  gtk_widget_show (button4_supp_rec);
  gtk_container_add (GTK_CONTAINER (eventbox3), button4_supp_rec);
  gtk_widget_set_size_request (button4_supp_rec, 224, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button4_supp_rec), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_box_pack_start (GTK_BOX (hbox3), eventbox5, FALSE, FALSE, 0);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (eventbox5), image4);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_box_pack_start (GTK_BOX (hbox3), eventbox4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer une reclamation"));
  gtk_widget_show (label4);
  gtk_container_add (GTK_CONTAINER (eventbox4), label4);

  eventbox10 = gtk_event_box_new ();
  gtk_widget_show (eventbox10);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox10, 72, 32);
  gtk_widget_set_size_request (eventbox10, 41, 17);

  label1_cin = gtk_label_new (_("CIN:"));
  gtk_widget_show (label1_cin);
  gtk_container_add (GTK_CONTAINER (eventbox10), label1_cin);
  gtk_widget_set_size_request (label1_cin, 41, 17);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_show (eventbox11);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox11, 288, 24);
  gtk_widget_set_size_request (eventbox11, 48, 32);

  button1_recherche = gtk_button_new ();
  gtk_widget_show (button1_recherche);
  gtk_container_add (GTK_CONTAINER (eventbox11), button1_recherche);
  gtk_widget_set_size_request (button1_recherche, 48, 32);

  eventbox12 = gtk_event_box_new ();
  gtk_widget_show (eventbox12);
  gtk_container_add (GTK_CONTAINER (button1_recherche), eventbox12);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (eventbox12), image1);

  image8 = create_pixmap (window_afficher, "l1060302.jpg");
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed1), image8, 0, 0);
  gtk_widget_set_size_request (image8, 736, 544);

  g_signal_connect ((gpointer) button3_modif_rec, "clicked",
                    G_CALLBACK (on_button3_modif_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_ajout_rec, "clicked",
                    G_CALLBACK (on_button2_ajout_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_supp_rec, "clicked",
                    G_CALLBACK (on_button4_supp_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_recherche, "clicked",
                    G_CALLBACK (on_button1_recherche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_afficher, window_afficher, "window_afficher");
  GLADE_HOOKUP_OBJECT (window_afficher, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window_afficher, entry1_recherche, "entry1_recherche");
  GLADE_HOOKUP_OBJECT (window_afficher, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window_afficher, treeview_reclam, "treeview_reclam");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window_afficher, button3_modif_rec, "button3_modif_rec");
  GLADE_HOOKUP_OBJECT (window_afficher, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_afficher, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (window_afficher, image3, "image3");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (window_afficher, label3, "label3");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (window_afficher, button2_ajout_rec, "button2_ajout_rec");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (window_afficher, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_afficher, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window_afficher, image2, "image2");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (window_afficher, label2, "label2");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (window_afficher, button4_supp_rec, "button4_supp_rec");
  GLADE_HOOKUP_OBJECT (window_afficher, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_afficher, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (window_afficher, image4, "image4");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (window_afficher, label4, "label4");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox10, "eventbox10");
  GLADE_HOOKUP_OBJECT (window_afficher, label1_cin, "label1_cin");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (window_afficher, button1_recherche, "button1_recherche");
  GLADE_HOOKUP_OBJECT (window_afficher, eventbox12, "eventbox12");
  GLADE_HOOKUP_OBJECT (window_afficher, image1, "image1");
  GLADE_HOOKUP_OBJECT (window_afficher, image8, "image8");

  return window_afficher;
}

GtkWidget*
create_window_gestion (void)
{
  GtkWidget *window_gestion;
  GtkWidget *fixed2;
  GtkWidget *entry2_id_rec;
  GtkWidget *entry3_cin_rec;
  GtkWidget *entry4_nom_rec;
  GtkWidget *entry5_prenom_rec;
  GtkObject *spinbutton1_jour_adj;
  GtkWidget *spinbutton1_jour;
  GtkObject *spinbutton2_mois_adj;
  GtkWidget *spinbutton2_mois;
  GtkObject *spinbutton3_annee_adj;
  GtkWidget *spinbutton3_annee;
  GtkWidget *entry6_text_rec;
  GtkWidget *eventbox13;
  GtkWidget *label5_id_rec;
  GtkWidget *eventbox14;
  GtkWidget *label6_cin_rec;
  GtkWidget *eventbox15;
  GtkWidget *label7_nom_rec;
  GtkWidget *eventbox16;
  GtkWidget *label9_type_rec;
  GtkWidget *eventbox17;
  GtkWidget *label8_prenom;
  GtkWidget *eventbox18;
  GtkWidget *label14_jour;
  GtkWidget *eventbox19;
  GtkWidget *label15_mois;
  GtkWidget *eventbox20;
  GtkWidget *label16_annee;
  GtkWidget *eventbox21;
  GtkWidget *label10_date_rec;
  GtkWidget *eventbox22;
  GtkWidget *label11_text_rec;
  GtkWidget *eventbox23;
  GtkWidget *label12_satisfaction;
  GtkWidget *eventbox24;
  GtkWidget *radiobutton1_satisfait;
  GSList *radiobutton1_satisfait_group = NULL;
  GtkWidget *eventbox25;
  GtkWidget *radiobutton2_non_satisfait;
  GtkWidget *eventbox26;
  GtkWidget *label13_education;
  GtkWidget *eventbox27;
  GtkWidget *checkbutton1_prep;
  GtkWidget *eventbox28;
  GtkWidget *checkbutton2_cycle_ing;
  GtkWidget *eventbox29;
  GtkWidget *checkbutton3_business;
  GtkWidget *eventbox30;
  GtkWidget *button6_ajouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *eventbox31;
  GtkWidget *image5;
  GtkWidget *eventbox32;
  GtkWidget *label17;
  GtkWidget *eventbox33;
  GtkWidget *button7_modifier;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *eventbox34;
  GtkWidget *image6;
  GtkWidget *eventbox35;
  GtkWidget *label18;
  GtkWidget *eventbox36;
  GtkWidget *button8_afficher;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *eventbox37;
  GtkWidget *image7;
  GtkWidget *eventbox38;
  GtkWidget *label19;
  GtkWidget *eventbox39;
  GtkWidget *combobox_rec;
  GtkWidget *image9;

  window_gestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_gestion), _("window_gestion"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window_gestion), fixed2);

  entry2_id_rec = gtk_entry_new ();
  gtk_widget_show (entry2_id_rec);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2_id_rec, 88, 16);
  gtk_widget_set_size_request (entry2_id_rec, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_id_rec), 8226);

  entry3_cin_rec = gtk_entry_new ();
  gtk_widget_show (entry3_cin_rec);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3_cin_rec, 88, 56);
  gtk_widget_set_size_request (entry3_cin_rec, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3_cin_rec), 8226);

  entry4_nom_rec = gtk_entry_new ();
  gtk_widget_show (entry4_nom_rec);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4_nom_rec, 88, 96);
  gtk_widget_set_size_request (entry4_nom_rec, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_nom_rec), 8226);

  entry5_prenom_rec = gtk_entry_new ();
  gtk_widget_show (entry5_prenom_rec);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5_prenom_rec, 328, 96);
  gtk_widget_set_size_request (entry5_prenom_rec, 184, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5_prenom_rec), 8226);

  spinbutton1_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_jour_adj), 1, 0);
  gtk_widget_show (spinbutton1_jour);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1_jour, 96, 216);
  gtk_widget_set_size_request (spinbutton1_jour, 56, 24);

  spinbutton2_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_mois_adj), 1, 0);
  gtk_widget_show (spinbutton2_mois);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton2_mois, 208, 216);
  gtk_widget_set_size_request (spinbutton2_mois, 60, 27);

  spinbutton3_annee_adj = gtk_adjustment_new (1990, 1990, 2030, 1, 10, 10);
  spinbutton3_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_annee_adj), 1, 0);
  gtk_widget_show (spinbutton3_annee);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3_annee, 312, 216);
  gtk_widget_set_size_request (spinbutton3_annee, 60, 27);

  entry6_text_rec = gtk_entry_new ();
  gtk_widget_show (entry6_text_rec);
  gtk_fixed_put (GTK_FIXED (fixed2), entry6_text_rec, 104, 256);
  gtk_widget_set_size_request (entry6_text_rec, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6_text_rec), 8226);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_show (eventbox13);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox13, 48, 24);
  gtk_widget_set_size_request (eventbox13, 41, 17);

  label5_id_rec = gtk_label_new (_("ID"));
  gtk_widget_show (label5_id_rec);
  gtk_container_add (GTK_CONTAINER (eventbox13), label5_id_rec);
  gtk_widget_set_size_request (label5_id_rec, 41, 17);

  eventbox14 = gtk_event_box_new ();
  gtk_widget_show (eventbox14);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox14, 48, 64);
  gtk_widget_set_size_request (eventbox14, 41, 17);

  label6_cin_rec = gtk_label_new (_("CIN"));
  gtk_widget_show (label6_cin_rec);
  gtk_container_add (GTK_CONTAINER (eventbox14), label6_cin_rec);
  gtk_widget_set_size_request (label6_cin_rec, 41, 17);

  eventbox15 = gtk_event_box_new ();
  gtk_widget_show (eventbox15);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox15, 48, 104);
  gtk_widget_set_size_request (eventbox15, 41, 17);

  label7_nom_rec = gtk_label_new (_("Nom"));
  gtk_widget_show (label7_nom_rec);
  gtk_container_add (GTK_CONTAINER (eventbox15), label7_nom_rec);
  gtk_widget_set_size_request (label7_nom_rec, 41, 17);

  eventbox16 = gtk_event_box_new ();
  gtk_widget_show (eventbox16);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox16, 48, 144);
  gtk_widget_set_size_request (eventbox16, 41, 17);

  label9_type_rec = gtk_label_new (_("Type"));
  gtk_widget_show (label9_type_rec);
  gtk_container_add (GTK_CONTAINER (eventbox16), label9_type_rec);
  gtk_widget_set_size_request (label9_type_rec, 41, 17);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_show (eventbox17);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox17, 256, 104);
  gtk_widget_set_size_request (eventbox17, 64, 16);

  label8_prenom = gtk_label_new (_("Prenom"));
  gtk_widget_show (label8_prenom);
  gtk_container_add (GTK_CONTAINER (eventbox17), label8_prenom);
  gtk_widget_set_size_request (label8_prenom, 64, 16);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_show (eventbox18);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox18, 96, 184);
  gtk_widget_set_size_request (eventbox18, 49, 17);

  label14_jour = gtk_label_new (_("Jour"));
  gtk_widget_show (label14_jour);
  gtk_container_add (GTK_CONTAINER (eventbox18), label14_jour);
  gtk_widget_set_size_request (label14_jour, 49, 17);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_show (eventbox19);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox19, 208, 184);
  gtk_widget_set_size_request (eventbox19, 49, 17);

  label15_mois = gtk_label_new (_("Mois"));
  gtk_widget_show (label15_mois);
  gtk_container_add (GTK_CONTAINER (eventbox19), label15_mois);
  gtk_widget_set_size_request (label15_mois, 49, 17);

  eventbox20 = gtk_event_box_new ();
  gtk_widget_show (eventbox20);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox20, 312, 184);
  gtk_widget_set_size_request (eventbox20, 49, 17);

  label16_annee = gtk_label_new (_("Annee"));
  gtk_widget_show (label16_annee);
  gtk_container_add (GTK_CONTAINER (eventbox20), label16_annee);
  gtk_widget_set_size_request (label16_annee, 49, 17);

  eventbox21 = gtk_event_box_new ();
  gtk_widget_show (eventbox21);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox21, 40, 216);
  gtk_widget_set_size_request (eventbox21, 49, 17);

  label10_date_rec = gtk_label_new (_("Date"));
  gtk_widget_show (label10_date_rec);
  gtk_container_add (GTK_CONTAINER (eventbox21), label10_date_rec);
  gtk_widget_set_size_request (label10_date_rec, 49, 17);

  eventbox22 = gtk_event_box_new ();
  gtk_widget_show (eventbox22);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox22, 0, 264);
  gtk_widget_set_size_request (eventbox22, 104, 16);

  label11_text_rec = gtk_label_new (_("Reclamation"));
  gtk_widget_show (label11_text_rec);
  gtk_container_add (GTK_CONTAINER (eventbox22), label11_text_rec);
  gtk_widget_set_size_request (label11_text_rec, 104, 16);

  eventbox23 = gtk_event_box_new ();
  gtk_widget_show (eventbox23);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox23, 0, 304);
  gtk_widget_set_size_request (eventbox23, 104, 16);

  label12_satisfaction = gtk_label_new (_("Satisfaction"));
  gtk_widget_show (label12_satisfaction);
  gtk_container_add (GTK_CONTAINER (eventbox23), label12_satisfaction);
  gtk_widget_set_size_request (label12_satisfaction, 104, 16);

  eventbox24 = gtk_event_box_new ();
  gtk_widget_show (eventbox24);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox24, 104, 296);
  gtk_widget_set_size_request (eventbox24, 116, 24);

  radiobutton1_satisfait = gtk_radio_button_new_with_mnemonic (NULL, _("satisfait"));
  gtk_widget_show (radiobutton1_satisfait);
  gtk_container_add (GTK_CONTAINER (eventbox24), radiobutton1_satisfait);
  gtk_widget_set_size_request (radiobutton1_satisfait, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_satisfait), radiobutton1_satisfait_group);
  radiobutton1_satisfait_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_satisfait));

  eventbox25 = gtk_event_box_new ();
  gtk_widget_show (eventbox25);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox25, 208, 296);
  gtk_widget_set_size_request (eventbox25, 116, 24);

  radiobutton2_non_satisfait = gtk_radio_button_new_with_mnemonic (NULL, _("non satisfait"));
  gtk_widget_show (radiobutton2_non_satisfait);
  gtk_container_add (GTK_CONTAINER (eventbox25), radiobutton2_non_satisfait);
  gtk_widget_set_size_request (radiobutton2_non_satisfait, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_non_satisfait), radiobutton1_satisfait_group);
  radiobutton1_satisfait_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_non_satisfait));

  eventbox26 = gtk_event_box_new ();
  gtk_widget_show (eventbox26);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox26, 8, 336);
  gtk_widget_set_size_request (eventbox26, 96, 16);

  label13_education = gtk_label_new (_("Education"));
  gtk_widget_show (label13_education);
  gtk_container_add (GTK_CONTAINER (eventbox26), label13_education);
  gtk_widget_set_size_request (label13_education, 96, 16);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox27, 96, 336);
  gtk_widget_set_size_request (eventbox27, 118, 24);

  checkbutton1_prep = gtk_check_button_new_with_mnemonic (_("Prepa"));
  gtk_widget_show (checkbutton1_prep);
  gtk_container_add (GTK_CONTAINER (eventbox27), checkbutton1_prep);
  gtk_widget_set_size_request (checkbutton1_prep, 118, 24);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_show (eventbox28);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox28, 176, 336);
  gtk_widget_set_size_request (eventbox28, 152, 24);

  checkbutton2_cycle_ing = gtk_check_button_new_with_mnemonic (_("Cycle d'ingenieur"));
  gtk_widget_show (checkbutton2_cycle_ing);
  gtk_container_add (GTK_CONTAINER (eventbox28), checkbutton2_cycle_ing);
  gtk_widget_set_size_request (checkbutton2_cycle_ing, 152, 24);

  eventbox29 = gtk_event_box_new ();
  gtk_widget_show (eventbox29);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox29, 320, 336);
  gtk_widget_set_size_request (eventbox29, 118, 24);

  checkbutton3_business = gtk_check_button_new_with_mnemonic (_("Business"));
  gtk_widget_show (checkbutton3_business);
  gtk_container_add (GTK_CONTAINER (eventbox29), checkbutton3_business);
  gtk_widget_set_size_request (checkbutton3_business, 118, 24);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_show (eventbox30);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox30, 40, 376);
  gtk_widget_set_size_request (eventbox30, 96, 32);

  button6_ajouter = gtk_button_new ();
  gtk_widget_show (button6_ajouter);
  gtk_container_add (GTK_CONTAINER (eventbox30), button6_ajouter);
  gtk_widget_set_size_request (button6_ajouter, 96, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button6_ajouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  eventbox31 = gtk_event_box_new ();
  gtk_widget_show (eventbox31);
  gtk_box_pack_start (GTK_BOX (hbox4), eventbox31, FALSE, FALSE, 0);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (eventbox31), image5);

  eventbox32 = gtk_event_box_new ();
  gtk_widget_show (eventbox32);
  gtk_box_pack_start (GTK_BOX (hbox4), eventbox32, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label17);
  gtk_container_add (GTK_CONTAINER (eventbox32), label17);

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox33, 152, 376);
  gtk_widget_set_size_request (eventbox33, 96, 32);

  button7_modifier = gtk_button_new ();
  gtk_widget_show (button7_modifier);
  gtk_container_add (GTK_CONTAINER (eventbox33), button7_modifier);
  gtk_widget_set_size_request (button7_modifier, 96, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button7_modifier), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_box_pack_start (GTK_BOX (hbox5), eventbox34, FALSE, FALSE, 0);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (eventbox34), image6);

  eventbox35 = gtk_event_box_new ();
  gtk_widget_show (eventbox35);
  gtk_box_pack_start (GTK_BOX (hbox5), eventbox35, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label18);
  gtk_container_add (GTK_CONTAINER (eventbox35), label18);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox36, 264, 376);
  gtk_widget_set_size_request (eventbox36, 96, 32);

  button8_afficher = gtk_button_new ();
  gtk_widget_show (button8_afficher);
  gtk_container_add (GTK_CONTAINER (eventbox36), button8_afficher);
  gtk_widget_set_size_request (button8_afficher, 96, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button8_afficher), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  eventbox37 = gtk_event_box_new ();
  gtk_widget_show (eventbox37);
  gtk_box_pack_start (GTK_BOX (hbox6), eventbox37, FALSE, FALSE, 0);

  image7 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (eventbox37), image7);

  eventbox38 = gtk_event_box_new ();
  gtk_widget_show (eventbox38);
  gtk_box_pack_start (GTK_BOX (hbox6), eventbox38, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label19);
  gtk_container_add (GTK_CONTAINER (eventbox38), label19);

  eventbox39 = gtk_event_box_new ();
  gtk_widget_show (eventbox39);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox39, 88, 136);
  gtk_widget_set_size_request (eventbox39, 160, 32);

  combobox_rec = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_rec);
  gtk_container_add (GTK_CONTAINER (eventbox39), combobox_rec);
  gtk_widget_set_size_request (combobox_rec, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_rec), _("Service hebergement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_rec), _("Service restauration"));

  image9 = create_pixmap (window_gestion, "l1060302.jpg");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed2), image9, 0, 0);
  gtk_widget_set_size_request (image9, 736, 544);

  g_signal_connect ((gpointer) radiobutton1_satisfait, "toggled",
                    G_CALLBACK (on_radiobutton1_satisfait_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2_non_satisfait, "toggled",
                    G_CALLBACK (on_radiobutton2_non_satisfait_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1_prep, "toggled",
                    G_CALLBACK (on_checkbutton1_prep_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2_cycle_ing, "toggled",
                    G_CALLBACK (on_checkbutton2_cycle_ing_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3_business, "toggled",
                    G_CALLBACK (on_checkbutton3_business_toggled),
                    NULL);
  g_signal_connect ((gpointer) button6_ajouter, "clicked",
                    G_CALLBACK (on_button6_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7_modifier, "clicked",
                    G_CALLBACK (on_button7_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8_afficher, "clicked",
                    G_CALLBACK (on_button8_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_gestion, window_gestion, "window_gestion");
  GLADE_HOOKUP_OBJECT (window_gestion, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_gestion, entry2_id_rec, "entry2_id_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, entry3_cin_rec, "entry3_cin_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, entry4_nom_rec, "entry4_nom_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, entry5_prenom_rec, "entry5_prenom_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, spinbutton1_jour, "spinbutton1_jour");
  GLADE_HOOKUP_OBJECT (window_gestion, spinbutton2_mois, "spinbutton2_mois");
  GLADE_HOOKUP_OBJECT (window_gestion, spinbutton3_annee, "spinbutton3_annee");
  GLADE_HOOKUP_OBJECT (window_gestion, entry6_text_rec, "entry6_text_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (window_gestion, label5_id_rec, "label5_id_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox14, "eventbox14");
  GLADE_HOOKUP_OBJECT (window_gestion, label6_cin_rec, "label6_cin_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (window_gestion, label7_nom_rec, "label7_nom_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (window_gestion, label9_type_rec, "label9_type_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (window_gestion, label8_prenom, "label8_prenom");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (window_gestion, label14_jour, "label14_jour");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (window_gestion, label15_mois, "label15_mois");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox20, "eventbox20");
  GLADE_HOOKUP_OBJECT (window_gestion, label16_annee, "label16_annee");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox21, "eventbox21");
  GLADE_HOOKUP_OBJECT (window_gestion, label10_date_rec, "label10_date_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox22, "eventbox22");
  GLADE_HOOKUP_OBJECT (window_gestion, label11_text_rec, "label11_text_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (window_gestion, label12_satisfaction, "label12_satisfaction");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox24, "eventbox24");
  GLADE_HOOKUP_OBJECT (window_gestion, radiobutton1_satisfait, "radiobutton1_satisfait");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (window_gestion, radiobutton2_non_satisfait, "radiobutton2_non_satisfait");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (window_gestion, label13_education, "label13_education");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (window_gestion, checkbutton1_prep, "checkbutton1_prep");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (window_gestion, checkbutton2_cycle_ing, "checkbutton2_cycle_ing");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox29, "eventbox29");
  GLADE_HOOKUP_OBJECT (window_gestion, checkbutton3_business, "checkbutton3_business");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (window_gestion, button6_ajouter, "button6_ajouter");
  GLADE_HOOKUP_OBJECT (window_gestion, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_gestion, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox31, "eventbox31");
  GLADE_HOOKUP_OBJECT (window_gestion, image5, "image5");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox32, "eventbox32");
  GLADE_HOOKUP_OBJECT (window_gestion, label17, "label17");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (window_gestion, button7_modifier, "button7_modifier");
  GLADE_HOOKUP_OBJECT (window_gestion, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_gestion, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (window_gestion, image6, "image6");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox35, "eventbox35");
  GLADE_HOOKUP_OBJECT (window_gestion, label18, "label18");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (window_gestion, button8_afficher, "button8_afficher");
  GLADE_HOOKUP_OBJECT (window_gestion, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window_gestion, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox37, "eventbox37");
  GLADE_HOOKUP_OBJECT (window_gestion, image7, "image7");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox38, "eventbox38");
  GLADE_HOOKUP_OBJECT (window_gestion, label19, "label19");
  GLADE_HOOKUP_OBJECT (window_gestion, eventbox39, "eventbox39");
  GLADE_HOOKUP_OBJECT (window_gestion, combobox_rec, "combobox_rec");
  GLADE_HOOKUP_OBJECT (window_gestion, image9, "image9");

  return window_gestion;
}

GtkWidget*
create_dialog_ok_aj (void)
{
  GtkWidget *dialog_ok_aj;
  GtkWidget *dialog_vbox1;
  GtkWidget *fixed3;
  GtkWidget *label20;
  GtkWidget *dialog_action_area1;
  GtkWidget *closebutton1;

  dialog_ok_aj = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_ok_aj), _("dialog1"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_ok_aj), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_ok_aj), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog_ok_aj)->vbox;
  gtk_widget_show (dialog_vbox1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), fixed3, TRUE, TRUE, 0);

  label20 = gtk_label_new (_("Ajout avec succ\303\251"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 64, 80);
  gtk_widget_set_size_request (label20, 160, 24);

  dialog_action_area1 = GTK_DIALOG (dialog_ok_aj)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  closebutton1 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_ok_aj), closebutton1, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) closebutton1, "clicked",
                    G_CALLBACK (on_closebutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ok_aj, dialog_ok_aj, "dialog_ok_aj");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ok_aj, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog_ok_aj, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (dialog_ok_aj, label20, "label20");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ok_aj, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog_ok_aj, closebutton1, "closebutton1");

  return dialog_ok_aj;
}

GtkWidget*
create_dialog_pb_aj (void)
{
  GtkWidget *dialog_pb_aj;
  GtkWidget *dialog_vbox2;
  GtkWidget *fixed4;
  GtkWidget *label21;
  GtkWidget *dialog_action_area2;
  GtkWidget *closebutton2;

  dialog_pb_aj = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_pb_aj), _("dialog2"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_pb_aj), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_pb_aj), FALSE);

  dialog_vbox2 = GTK_DIALOG (dialog_pb_aj)->vbox;
  gtk_widget_show (dialog_vbox2);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), fixed4, TRUE, TRUE, 0);

  label21 = gtk_label_new (_("ID EXISTE DEJA"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 80, 80);
  gtk_widget_set_size_request (label21, 144, 16);

  dialog_action_area2 = GTK_DIALOG (dialog_pb_aj)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  closebutton2 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_pb_aj), closebutton2, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton2, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) closebutton2, "clicked",
                    G_CALLBACK (on_closebutton2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_pb_aj, dialog_pb_aj, "dialog_pb_aj");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_pb_aj, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog_pb_aj, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (dialog_pb_aj, label21, "label21");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_pb_aj, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog_pb_aj, closebutton2, "closebutton2");

  return dialog_pb_aj;
}

GtkWidget*
create_dialog_ok_modif (void)
{
  GtkWidget *dialog_ok_modif;
  GtkWidget *dialog_vbox3;
  GtkWidget *fixed5;
  GtkWidget *label22;
  GtkWidget *dialog_action_area3;
  GtkWidget *closebutton3;

  dialog_ok_modif = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_ok_modif), _("dialog3"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_ok_modif), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_ok_modif), FALSE);

  dialog_vbox3 = GTK_DIALOG (dialog_ok_modif)->vbox;
  gtk_widget_show (dialog_vbox3);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), fixed5, TRUE, TRUE, 0);

  label22 = gtk_label_new (_("Modification avec succ\303\251e"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 48, 80);
  gtk_widget_set_size_request (label22, 200, 24);

  dialog_action_area3 = GTK_DIALOG (dialog_ok_modif)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  closebutton3 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton3);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_ok_modif), closebutton3, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton3, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) closebutton3, "clicked",
                    G_CALLBACK (on_closebutton3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ok_modif, dialog_ok_modif, "dialog_ok_modif");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ok_modif, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog_ok_modif, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (dialog_ok_modif, label22, "label22");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ok_modif, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog_ok_modif, closebutton3, "closebutton3");

  return dialog_ok_modif;
}

GtkWidget*
create_dialog_pb_modif (void)
{
  GtkWidget *dialog_pb_modif;
  GtkWidget *dialog_vbox4;
  GtkWidget *fixed6;
  GtkWidget *label23;
  GtkWidget *dialog_action_area4;
  GtkWidget *closebutton4;

  dialog_pb_modif = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_pb_modif), _("dialog4"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog_pb_modif), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog_pb_modif), FALSE);

  dialog_vbox4 = GTK_DIALOG (dialog_pb_modif)->vbox;
  gtk_widget_show (dialog_vbox4);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), fixed6, TRUE, TRUE, 0);

  label23 = gtk_label_new (_("ID N'EXISTE PAS"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed6), label23, 72, 96);
  gtk_widget_set_size_request (label23, 144, 16);

  dialog_action_area4 = GTK_DIALOG (dialog_pb_modif)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  closebutton4 = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (closebutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_pb_modif), closebutton4, GTK_RESPONSE_CLOSE);
  GTK_WIDGET_SET_FLAGS (closebutton4, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) closebutton4, "clicked",
                    G_CALLBACK (on_closebutton4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_pb_modif, dialog_pb_modif, "dialog_pb_modif");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_pb_modif, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (dialog_pb_modif, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (dialog_pb_modif, label23, "label23");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_pb_modif, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (dialog_pb_modif, closebutton4, "closebutton4");

  return dialog_pb_modif;
}

